version: '3.8'

services:
  eureka-discovery-service:
    build:
      context: ../..
      dockerfile: docker/stg/stg-deploy.Dockerfile
    ports:
      - "8762:8762"

networks:
  default:
    external: true
    name: aimcup-network