version: '3.8'

services:
  eureka-discovery-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
#      - "5005:5005"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

networks:
  default:
    external: true
    name: aimcup-network