version: '3.8'

services:
  eureka-discovery-service:
    build:
      context: ../..
      dockerfile: docker/prd/prd-deploy.Dockerfile
    ports:
      - "8761:8761"

networks:
  default:
    external: true
    name: aimcup-network