name: Deploy to Staging

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:
  build:
    runs-on:
      group: Default
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker-compose -f docker/stg/stg-deploy-job.yml up -d --build